"""
Localiza el perfil Firefox "TemazoBot" y syncroniza sus cookies YouTube al VPS.
Sustituye a sync_cookies.py cuando existe un perfil dedicado (evita rotacion YT).
"""
import os, sys, glob, sqlite3, shutil, tempfile, socket, datetime, logging, traceback

LOG_DIR = os.path.join(os.environ.get("LOCALAPPDATA", tempfile.gettempdir()), "TemazoCookieSync")
os.makedirs(LOG_DIR, exist_ok=True)
logging.basicConfig(
    filename=os.path.join(LOG_DIR, "sync.log"),
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)

VPS_HOST = "217.160.32.162"
VPS_USER = "root"
VPS_PASS = os.environ.get("TEMAZO_VPS_PASS", "O1LyJoEnG58o")
VPS_DIR = "/var/www/vhosts/temazo.es/private/cookies"
VPS_OWNER = "temazo.es_w9ylvfjs6yd:psaserv"

PROFILE_NAME = "TemazoBot"
CRITICAL = {"SAPISID", "HSID", "SSID", "APISID", "SID",
            "__Secure-1PSID", "__Secure-3PSID"}


def find_bot_profile():
    """Busca el path del perfil Firefox llamado TemazoBot."""
    ff_dir = os.path.join(os.environ["APPDATA"], "Mozilla", "Firefox", "Profiles")
    candidates = glob.glob(os.path.join(ff_dir, f"*.{PROFILE_NAME}"))
    # Firefox también nombra a veces como *.temazobot-default
    if not candidates:
        candidates = [d for d in glob.glob(os.path.join(ff_dir, "*"))
                      if PROFILE_NAME.lower() in os.path.basename(d).lower()]
    if not candidates:
        raise RuntimeError(f"No se encuentra perfil Firefox llamado '{PROFILE_NAME}'. Crea uno con about:profiles y logueate con la cuenta burner.")
    return candidates[0]


def read_cookies_from_profile(profile_path: str):
    db_path = os.path.join(profile_path, "cookies.sqlite")
    if not os.path.isfile(db_path):
        raise RuntimeError(f"No hay cookies.sqlite en {profile_path}. Loguea en YouTube desde ese perfil una vez.")
    # Copia del DB para leer sin lock si Firefox esta abierto
    tmp_db = tempfile.mktemp(suffix=".sqlite")
    shutil.copy2(db_path, tmp_db)
    conn = sqlite3.connect(tmp_db)
    conn.row_factory = sqlite3.Row
    try:
        rows = conn.execute(
            "SELECT host, path, isSecure, expiry, name, value FROM moz_cookies "
            "WHERE host LIKE '%youtube.com%' OR host LIKE '%google.com%'"
        ).fetchall()
    finally:
        conn.close()
        try: os.unlink(tmp_db)
        except: pass
    logging.info(f"Cookies leidas del perfil: {len(rows)}")
    names = {r["name"] for r in rows}
    logging.info(f"Login cookies presentes: {sorted(CRITICAL & names)}")
    if "SAPISID" not in names:
        raise RuntimeError("Perfil TemazoBot NO tiene sesion YouTube. Abre Firefox con ese perfil, ve a youtube.com, loguea burner, cierra.")
    return rows


def to_netscape(rows):
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by Temazo find_and_sync_bot_profile.py",
        f"# Sync: {datetime.datetime.utcnow().isoformat()}Z",
        f"# Profile: {PROFILE_NAME}",
        "",
    ]
    for r in rows:
        host = r["host"] if r["host"].startswith(".") else "." + r["host"].lstrip(".")
        include_sub = "TRUE"
        path = r["path"] or "/"
        secure = "TRUE" if r["isSecure"] else "FALSE"
        expires = int(r["expiry"]) if r["expiry"] else 0
        name = r["name"]
        value = r["value"] or ""
        lines.append("\t".join([host, include_sub, path, secure, str(expires), name, value]))
    return "\n".join(lines) + "\n"


def upload_to_vps(content: str, hostname: str):
    import paramiko
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    client.connect(VPS_HOST, username=VPS_USER, password=VPS_PASS, timeout=20)
    client.exec_command(f"mkdir -p {VPS_DIR}")
    sftp = client.open_sftp()
    remote_path = f"{VPS_DIR}/owner_{hostname}.txt"
    tmp_path = remote_path + ".tmp"
    with sftp.file(tmp_path, "w") as f:
        f.write(content)
    sftp.chmod(tmp_path, 0o600)
    client.exec_command(
        f"mv {tmp_path} {remote_path} && "
        f"chown {VPS_OWNER} {remote_path} && "
        f"chmod 600 {remote_path}"
    )
    sftp.close()
    client.close()
    logging.info(f"Uploaded {remote_path} ({len(content)} bytes)")
    return remote_path


def main():
    try:
        hostname = socket.gethostname().lower().replace(" ", "_")[:32]
        logging.info(f"=== BotProfile sync start hostname={hostname} ===")
        profile = find_bot_profile()
        logging.info(f"Perfil localizado: {profile}")
        rows = read_cookies_from_profile(profile)
        content = to_netscape(rows)
        path = upload_to_vps(content, hostname)
        print(f"OK cookies subidas a {path} ({len(content)} bytes)")
        logging.info("=== BotProfile sync OK ===")
        sys.exit(0)
    except Exception as e:
        print(f"ERROR: {e}")
        logging.error(f"Sync FAIL: {e}\n{traceback.format_exc()}")
        sys.exit(1)


if __name__ == "__main__":
    main()
