"""
Auto-sync de cookies YouTube: Chrome (Windows) -> VPS Temazo
Corre cada 12h via Task Scheduler como SYSTEM (permisos DPAPI).

Flujo:
 1. Lee cookies youtube.com del Chrome local con browser_cookie3
 2. Convierte a formato Netscape (yt-dlp compatible)
 3. Sube por SFTP a /opt/piped-prod/cookies/owner_<HOSTNAME>.txt
 4. Log local en %LOCALAPPDATA%\TemazoCookieSync\sync.log

Requisitos:
 pip install browser_cookie3 paramiko

Task Scheduler:
 Run as SYSTEM, con "Run with highest privileges"
 Trigger: cada 12 horas
"""
import os, sys, socket, datetime, tempfile, logging, traceback

# Log a %LOCALAPPDATA%
LOG_DIR = os.path.join(os.environ.get("LOCALAPPDATA", tempfile.gettempdir()), "TemazoCookieSync")
os.makedirs(LOG_DIR, exist_ok=True)
LOG_FILE = os.path.join(LOG_DIR, "sync.log")
logging.basicConfig(
    filename=LOG_FILE, level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)

VPS_HOST = "217.160.32.162"
VPS_USER = "root"
VPS_PASS = os.environ.get("TEMAZO_VPS_PASS", "O1LyJoEnG58o")
VPS_DIR = "/var/www/vhosts/temazo.es/private/cookies"
VPS_OWNER = "temazo.es_w9ylvfjs6yd:psaserv"  # user Plesk del sitio

CRITICAL_COOKIES = {"SAPISID", "HSID", "SSID", "APISID", "SID",
                    "__Secure-1PSID", "__Secure-3PSID",
                    "__Secure-1PAPISID", "__Secure-3PAPISID"}


def extract_cookies():
    """Firefox: SQLite plain, sin App-Bound Encryption, sin admin.
    Chrome 127+ tiene App-Bound => usamos Firefox como fuente oficial."""
    import browser_cookie3
    cj = browser_cookie3.firefox(domain_name="youtube.com")
    cookies = list(cj)
    names = {c.name for c in cookies}
    missing = CRITICAL_COOKIES - names
    logging.info(f"Cookies extraidas: {len(cookies)}")
    logging.info(f"Login cookies presentes: {sorted(CRITICAL_COOKIES & names)}")
    if "SAPISID" not in names:
        logging.warning("No hay cookie SAPISID => sesion YT no logueada. Aborta.")
        return None
    return cookies


def to_netscape(cookies):
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by Temazo cookie_sync.py",
        f"# Sync: {datetime.datetime.utcnow().isoformat()}Z",
        "",
    ]
    for c in cookies:
        domain = c.domain if c.domain.startswith(".") else "." + c.domain.lstrip(".")
        include_sub = "TRUE"
        path = c.path or "/"
        secure = "TRUE" if c.secure else "FALSE"
        expires = int(c.expires) if c.expires else 0
        name = c.name
        value = c.value or ""
        lines.append("\t".join([domain, include_sub, path, secure, str(expires), name, value]))
    return "\n".join(lines) + "\n"


def upload_to_vps(netscape_content: str, hostname: str):
    import paramiko
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    client.connect(VPS_HOST, username=VPS_USER, password=VPS_PASS, timeout=20)
    # Asegurar dir existe con permisos 700
    client.exec_command(f"mkdir -p {VPS_DIR} && chmod 700 {VPS_DIR}")
    sftp = client.open_sftp()
    remote_path = f"{VPS_DIR}/owner_{hostname}.txt"
    tmp_path = remote_path + ".tmp"
    with sftp.file(tmp_path, "w") as f:
        f.write(netscape_content)
    sftp.chmod(tmp_path, 0o600)
    # Rename atomico + fix ownership al user Plesk del sitio
    client.exec_command(
        f"mv {tmp_path} {remote_path} && "
        f"chown {VPS_OWNER} {remote_path} && "
        f"chmod 600 {remote_path}"
    )
    sftp.close()
    client.close()
    logging.info(f"Uploaded => {remote_path} ({len(netscape_content)} bytes)")


def main():
    try:
        hostname = socket.gethostname().lower().replace(" ", "_")[:32]
        logging.info(f"=== Sync start hostname={hostname} ===")
        cookies = extract_cookies()
        if not cookies:
            logging.error("Abort: no critical cookies")
            sys.exit(2)
        netscape = to_netscape(cookies)
        upload_to_vps(netscape, hostname)
        logging.info(f"=== Sync OK ===")
        sys.exit(0)
    except Exception as e:
        logging.error(f"Sync FAIL: {e}\n{traceback.format_exc()}")
        sys.exit(1)


if __name__ == "__main__":
    main()
